services:
  - name: png-back
    type: web
    instance_type: nano
    regions:
      - fra
    env:
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - JWT_SECRET
    ports:
      - port: 3000
        protocol: http
    routes:
      - path: /
        port: 3000
    health_check:
      http:
        path: /api/health
        port: 3000
    autoscaling:
      min: 1
      max: 1
