# Coturn TURN/STUN 配置 - 与 ScreenShare.tsx 中 ZIYE_ICE_SERVERS 账号密码一致
listening-port=3478
fingerprint
lt-cred-mech
user=screen123:share666
realm=ziye-stream
no-cli
no-tls
no-dtls
# install.sh 会自动替换 __PUBLIC_IP__
external-ip=__PUBLIC_IP__
relay-ip=__PUBLIC_IP__
min-port=49152
max-port=65535
verbose
